// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgirvsrazocpqanyhtnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnaXJ2c3Jhem9jcHFhbnlodG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDE1MDYsImV4cCI6MjA3MTg3NzUwNn0.spOs5KBtUxN8Ncym8DoakYH-8iFMD6wDKBgBMe_Xl1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});